### ISSUE TITLE
regenbogen-ice rss won't work

### ISSUE THREAD

**Issue by AdriDevelopsThings** [mikbot/hafalsch#4]
Sorry I don't know the libraries you used but I think the rss feature of regenbogen-ice won't work because you used the path `/rss` after `/api` so the full path would be `/api/rss`. But the regenbogen-ice rss feature is only available at `/rss`. (https://regenbogen-ice.de/rss ; https://regenbogen-ice.de/api/rss will show you a 404 error).

Look at this line: https://github.com/mikbot/hafalsch/blob/main/regenbogen-ice-client/src/commonMain/kotlin/dev/schlaubi/hafalsch/rainbow_ice/routes/RainbowICE.kt#L20

**Comment by DRSchlaubi** [comment]
Yep that's en oversight, thanks for noticing
